%% exportdata.m
% Exports digitized and net joint moment data from the '_short.mat' files
% that save all the data generated by the MatLab code Ian created.


%%
% gather all files ending in '*_short.mat'
cd('../data/data_mat_files')
files = dir('*_short.mat');

% loop through each file and output specific data
for cnt = 1:length(files)
    % load data
    load(files(cnt).name,...
        'elbow_ang_CROP', 'elb_vel_CROP', 'torso_ang_CROP', 'torso_vel_CROP'); % variables for reaction force
    
    % create table
    tab_out = array2table([elbow_ang_CROP, [0; elb_vel_CROP'], torso_ang_CROP, [0; torso_vel_CROP']],...
        'VariableNames', {'elbow_angle', 'elbow_angvel', 'torso_angle', 'torso_angvel'});
    
    % create new file name
    filename = ['../subject_njm_data/', files(cnt).name(1:length(files(cnt).name)-10), '.xlsx'];
    writetable(tab_out, filename)
    
    % clear vars
    clearvars -except files cnt
end